name: Worker-Farms
on:
  push:
    branches: 
      - test-ci
    paths:
      - 'api/farms/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build:packages

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          envkey_CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          envkey_U2U_TESTNET_NODE: ${{ vars.U2U_TESTNET_NODE }}        
          
          directory: .
          file_name: apis/farms/.env
          fail_on_empty: false

      - name: Build & Deploy Worker
        run: |
          cd apis/farms
          npm run deploy
